In [19]:
import pandas as pd
import pymysql as ms

In [20]:
data_fram = pd.read_csv("data/spotify-2023.csv",encoding="ISO-8859-1")

In [21]:
# data_fram.info()

In [22]:
# data_fram.columns
# data_fram.head

In [23]:
data_fram_filter = data_fram[["track_name",'artist(s)_name', 'artist_count','released_year',
       'released_month', 'released_day', 'in_spotify_playlists',
       'in_spotify_charts', 'streams']]

In [24]:
data_fram_filter.head()

,track_name,artist(s)_name,artist_count,released_year,released_month,released_day,in_spotify_playlists,in_spotify_charts,streams
0,Seven (feat. Latto) (Explicit Ver.),"Latto, Jung Kook",2,2023,7,14,553,147,141381703
1,LALA,Myke Towers,1,2023,3,23,1474,48,133716286
2,vampire,Olivia Rodrigo,1,2023,6,30,1397,113,140003974
3,Cruel Summer,Taylor Swift,1,2019,8,23,7858,100,800840817
4,WHERE SHE GOES,Bad Bunny,1,2023,5,18,3133,50,303236322

In [25]:
con = ms.connect(host="localhost",user="root",password="20btad036",db="spotify_db")
cur = con.cursor()

In [26]:
spotify_2023_table = """
create table if not exists spotify_2023 (
ent_id int primary key auto_increment,
track_name varchar(200),
artist_name varchar(200),
artist_count int,
released_year int,
released_month int,
released_day int,
in_playlists int,
in_charts int,
streams bigint
)
"""

In [27]:
cur.execute(spotify_2023_table)
con.commit()

In [28]:
insert_data = """
insert into spotify_2023 values (default,%s,%s,%s,%s,%s,%s,%s,%s,%s)
"""

for i,row in data_fram_filter.iterrows():
    # print(list(row))
    if list(row)[8].isdigit():
        cur.execute(insert_data,tuple(row))
        con.commit()

In [18]:
# cur.execute("drop table spotify_2023")
# con.commit()

In [42]:
def TopSongs_2023():
    sql = """
                 select
                        track_name,
                        artist_name,
                        in_playlists,
                        in_charts,
                        streams
                 from spotify_2023
                 where released_year = 2023
                 order by streams desc limit 10
          """
    cur.execute(sql)
    result = cur.fetchall()
    # return result
    for i in result:
        # print(i[0],i[1],i[2],i[3],i[4])
       # print(f"{i[0]:20}{i[1]:20}{i[2]:20}{i[3]:20}{i[4]:20}")
        print(i)

def TopArtists_2023():
    sql = """
                select
                    artist_name,
                    sum(streams) as streams,
                    sum(in_playlists) as playlist_count,
                    sum(in_charts) as charts_count
                from spotify_2023
                where released_year = 2023
                group by artist_name
                order by streams desc limit 10
          """
    cur.execute(sql)
    result = cur.fetchall()
    for i in result:
        print(i)
        
def most_songs_count_by_artist():
    sql = """
                SELECT 
                  artist_name,
                  COUNT(*) as song_count
                FROM spotify_2023
                WHERE released_year = 2023
                GROUP BY artist_name
                ORDER BY song_count DESC limit 10
          """
    cur.execute(sql)
    result = cur.fetchall()
    for i in result:
        print(i)

def average_number_of_streams():
    sql = """
                SELECT
                      released_month,
                      monthname(concat("2023-",released_month,"-01")) as month,
                      ROUND(AVG(streams),0) as avg_streams
                FROM spotify_2023
                WHERE released_year = 2023
                GROUP BY released_month
                ORDER BY released_month  
          """
    cur.execute(sql)
    result = cur.fetchall()
    for i in result:
        print(i)

In [43]:
TopSongs_2023()
# TopArtists_2023()
# most_songs_count_by_artist()
# average_number_of_streams()

('Flowers', 'Miley Cyrus', 12211, 115, 1316855716)
('Ella Baila Sola', 'Eslabon Armado, Peso Pluma', 3090, 50, 725980112)
('Shakira: Bzrp Music Sessions, Vol. 53', 'Shakira, Bizarrap', 5724, 44, 721975598)
('TQG', 'Karol G, Shakira', 4284, 49, 618990393)
('La Bebe - Remix', 'Peso Pluma, Yng Lvcas', 2953, 44, 553634067)
('Die For You - Remix', 'Ariana Grande, The Weeknd', 3408, 47, 518745108)
('un x100to', 'Bad Bunny, Grupo Frontera', 2876, 40, 505671438)
('Cupid - Twin Ver.', 'Fifty Fifty', 2942, 77, 496795686)
('PRC', 'Natanael Cano, Peso Pluma', 961, 26, 436027885)
('OMG', 'NewJeans', 1783, 27, 430977451)

In [46]:
print("SPOTIFY WRAPPED 2023")

# fun ={1:TopSongs_2023(),2:TopArtists_2023(),3:most_songs_count_by_artist(),4:average_number_of_streams()}

while(True):
    print("1.Top Songs of 2023")
    print("2.Top Artists of 2023")
    print("3.Artist has the most songs in the top streamed list of 2023")
    print("4.Average number of streams for songs released in each month of 2023")
    print("5.Quit")
    print("----------------------------------------------------------------------")
    print("Enter Your Option: ")
    opt = int(input())
    if(opt==1):
        TopSongs_2023()
    elif(opt==2):
        TopArtists_2023()
    elif(opt==3):
        most_songs_count_by_artist()
    elif(opt==4):
        average_number_of_streams()
    elif(opt==5):
        print("Thank You :)")
        break
    else:
        print("Wrong Option Choose the Correct One :(")
    print()
    print()

SPOTIFY WRAPPED 2023
1.Top Songs of 2023
2.Top Artists of 2023
3.Artist has the most songs in the top streamed list of 2023
4.Average number of streams for songs released in each month of 2023
5.Quit
----------------------------------------------------------------------
Enter Your Option:
4
(1, 'January', Decimal('287635464'))
(2, 'February', Decimal('231191625'))
(3, 'March', Decimal('170092262'))
(4, 'April', Decimal('150805436'))
(5, 'May', Decimal('94420746'))
(6, 'June', Decimal('70200253'))
(7, 'July', Decimal('41504666'))


1.Top Songs of 2023
2.Top Artists of 2023
3.Artist has the most songs in the top streamed list of 2023
4.Average number of streams for songs released in each month of 2023
5.Quit
----------------------------------------------------------------------
Enter Your Option:
7
Wrong Option Choose correct One :(


1.Top Songs of 2023
2.Top Artists of 2023
3.Artist has the most songs in the top streamed list of 2023
4.Average number of streams for songs released in each month of 2023
5.Quit
----------------------------------------------------------------------
Enter Your Option:
2
('Miley Cyrus', Decimal('1316855716'), Decimal('12211'), Decimal('115'))
('Morgan Wallen', Decimal('946694010'), Decimal('5040'), Decimal('29'))
('Eslabon Armado, Peso Pluma', Decimal('725980112'), Decimal('3090'), Decimal('50'))
('Shakira, Bizarrap', Decimal('721975598'), Decimal('5724'), Decimal('44'))
('Jimin', Decimal('705445695'), Decimal('1309'), Decimal('100'))
('Fifty Fifty', Decimal('636477650'), Decimal('3468'), Decimal('87'))
('Karol G, Shakira', Decimal('618990393'), Decimal('4284'), Decimal('49'))
('Peso Pluma, Yng Lvcas', Decimal('553634067'), Decimal('2953'), Decimal('44'))
('NewJeans', Decimal('518794821'), Decimal('2282'), Decimal('117'))
('Ariana Grande, The Weeknd', Decimal('518745108'), Decimal('3408'), Decimal('47'))


1.Top Songs of 2023
2.Top Artists of 2023
3.Artist has the most songs in the top streamed list of 2023
4.Average number of streams for songs released in each month of 2023
5.Quit
----------------------------------------------------------------------
Enter Your Option:
5
Thank You :)